CXX = g++
CXXFLAGS = -Wall -g
OBJS = postfix.o
TARGET = postfix

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

postfix.o: postfix.cpp linkedstack.h Node.h
	$(CXX) $(CXXFLAGS) -c postfix.cpp

clean:
	rm -f $(OBJS) $(TARGET)
