CXX = g++
CXXFLAGS = -Wall -g
OBJS = linkedstack.o Node.o postfix.o 
TARGET = postfix

$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

linkedstack.o: linkedstack.cpp linkedstack.h
	$(CXX) $(CXXFLAGS) -c linkedstack.cpp

Node.o: Node.cpp Node.h
	$(CXX) $(CXXFLAGS) -c Node.cpp

postfix.o: postfix.cpp linkedstack.h Node.h
	$(CXX) $(CXXFLAGS) -c postfix.cpp

clean:
	rm -f $(OBJS) $(TARGET)